update @walletconnect/ethereum-provider
wevm/wagmi pull request #3570
Opened 2024-02-06 13:29 UTC by svenvoskamp

## Description

update @walletconnect/ethereum-provider

## Additional Information

Before submitting this issue, please make sure you do the following.

- [x] Read the [contributing guide](https://wagmi.sh/dev/contributing)
- [x] Added documentation related to the changes made.
- [x] Added or updated tests (and snapshots) related to the changes made.

2024-02-09 21:03 UTC, SashaDesigN commented
Is this going to be approved in near future?

2024-02-09 21:11 UTC, tmm requested changes

2024-02-09 21:11 UTC, tmm commented on .changeset/stupid-numbers-guess.md
> +'@wagmi/connectors': major
```suggestion
'@wagmi/connectors': patch
```

2024-02-09 21:11 UTC, tmm commented on .changeset/stupid-numbers-guess.md
> +Update @walletconnect/ethereum-provider
```suggestion
Updated @walletconnect/ethereum-provider
```

2024-02-09 22:18 UTC, witalick22 commented
zalupa yobana, can you do this faster? Why so long?

2024-02-23 17:32 UTC, kolirt commented
When will wagmi-v1 be updated?

2024-03-02 08:48 UTC, kolirt commented
@tmm ?

2024-03-18 10:46 UTC, kolirt commented
@tmm any updates?

2024-03-21 08:31 UTC, kolirt commented
@tmm ?

2024-03-21 09:39 UTC, glitch-txs commented
better to upgrade to Wagmi v2, we'll keep upgrading and improving the library (ethereum-provider)

2024-03-21 09:41 UTC, kolirt commented
> better to upgrade to Wagmi v2, we'll keep upgrading and improving the library (ethereum-provider)

I can't upgrade to v2. Can u update v1 version?

2024-03-21 09:52 UTC, glitch-txs commented
You can try by using overrides or (resolutions in yarn)
https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides

2024-04-01 20:46 UTC, closed without merging