Add missing function name
wevm/wagmi pull request #3612
Opened 2024-02-19 06:05 UTC by m1heng

2024-02-21 14:38 UTC, tmm requested changes
Looks great! Can you create a patch changeset with `pnpm changeset`?

2024-02-22 07:07 UTC, m1heng commented
changeset added

2024-02-27 07:24 UTC, m1heng commented
@tmm maybe we can have this merged earlier so that I can remove the patch in my private repo

2024-02-28 16:13 UTC, jojoo-eth commented
Hello, I'm troubled by this issue. May I ask if it can be merged?

2024-03-18 22:34 UTC, kschrute commented
I'd appreciate it if this was merged as well.

2024-03-18 22:35 UTC, kschrute commented
@tmm

2024-03-21 04:20 UTC, tmm approved these changes

2024-03-21 04:20 UTC, tmm commented on .changeset/tiny-bees-own.md
> +Add missing function name in codegen function
```suggestion
Added missing `functionName` parameter to `useWriteContract` codegen helper.
```

2024-03-21 04:20 UTC, merged