docs: fraxtal api url
wevm/wagmi pull request #3633
Opened 2024-02-24 19:58 UTC by pegahcarter

## Description

Added fraxtal etherscan documentation.

## Additional Information

N/A

- [ ] Read the [contributing guide](https://wagmi.sh/dev/contributing)
- [ ] Added documentation related to the changes made.
- [ ] Added or updated tests (and snapshots) related to the changes made.

2024-02-24 20:13 UTC, tmm requested changes
Please add a patch changeset with `pnpm changeset`

2024-02-26 19:31 UTC, pegahcarter commented
cc @tmm

2024-03-03 17:58 UTC, tmm approved these changes

2024-03-03 17:58 UTC, tmm commented on .changeset/sharp-fans-refuse.md
> +build: fraxtal etherscan apiUrls
```suggestion
Added Fraxtal to Etherscan plugin
```

2024-03-03 17:58 UTC, merged