fix: correct project typos
wevm/wagmi pull request #4102
Opened 2024-06-30 00:10 UTC by ClumsyVlad

After analyzing the project code, typos in explanation comments and documentation files were found and corrected.

2024-06-30 18:59 UTC, tmm requested changes

2024-06-30 18:59 UTC, tmm commented on site/vue/typescript.md
> -  functionName: 'balanecOf',
This is intentional. Please revert this change.

2024-06-30 18:59 UTC, tmm commented on site/react/typescript.md
> -  functionName: 'balanecOf',
This is intentional. Please revert this change.

2024-06-30 18:59 UTC, tmm commented on site/core/typescript.md
> -  functionName: 'balanecOf',
This is intentional. Please revert this change.

2024-06-30 18:59 UTC, tmm commented on packages/core/src/actions/watchChains.ts
> - * We don't expose this because as far as consumers know, you can't chainge (lol) `config.chains` at runtime.
This is intentional. Please revert this change.

2024-07-01 13:09 UTC, ClumsyVlad commented
@tmm could you explain, please, why there should be the intentioan typo in `balanceOf` function name?
And also, why would you like to keep intentional typo in comment in watchChains.ts? 🤔

2024-07-01 15:04 UTC, tmm commented
> why there should be the intentioan typo in balanceOf function name?

This typo is intentional to [showcase Wagmi's type-safety](https://wagmi.sh/react/typescript#const-assert-abis-typed-data).

<img width="732" alt="image" src="https://github.com/wevm/wagmi/assets/6759464/57ad416a-22c3-4883-9c87-c414f5e4a743">

> why would you like to keep intentional typo in comment in watchChains.ts?

This is a joke we'd like to keep around.

2024-07-01 22:34 UTC, ClumsyVlad commented
> This typo is intentional to [showcase Wagmi's type-safety](https://wagmi.sh/react/typescript#const-assert-abis-typed-data).
Reverted 🫡
> This is a joke we'd like to keep around.
Reverted 🫡

2024-07-02 04:25 UTC, merged