FIX: useConnectorClient should only be enabled when connected
wevm/wagmi pull request #4124
Opened 2024-07-09 18:19 UTC by t0rbik

This PR aims to prevent `useConnectorClient` running when account is **not** in `connected` state.

Took this along as a quick fix, feel free to close if this is a desired behaviour. Cheers.

2024-07-17 21:15 UTC, tmm requested changes
Thanks! Let's add the same change (and changeset) for the [`useConnectorClient` Vue Composable](https://github.com/wevm/wagmi/blob/main/packages/vue/src/composables/useConnectorClient.ts#L100) too.

2024-07-17 21:15 UTC, tmm commented on packages/react/src/hooks/useConnectorClient.ts
> +  const enabled = Boolean(status === 'connected' && (query.enabled ?? true))
Agree with filtering out `'connecting'`. Let's add `'reconnecting'` here though as it enables optimistic updates.

2024-07-17 21:15 UTC, tmm commented on .changeset/short-eyes-hide.md
> +useConnectorClient only enabled when account status is 'connected'.
```suggestion
Updated `useConnectorClient` to enable when status is `'reconnecting'` or `'connected'` (previously was also enabled when status was `'connecting'`).
```

2024-07-18 11:23 UTC, t0rbik commented
Thank you, I've applied the suggestions.

2024-07-18 20:45 UTC, merged