Update coinbaseWallet.ts
wevm/wagmi pull request #4440
Opened 2024-12-06 12:49 UTC by johanneskares

This PR adds support for the instant onboarding mode of Coinbase Smart Wallet. It enables the same behaviour of the `Create Wallet` button on wallet.coinbase.com and skipping the first screen, where around 50% of my userbase clicked the wrong button. 

https://github.com/user-attachments/assets/1d38ad7d-e78a-42c1-84ce-aad1117fba41

2024-12-13 19:04 UTC, tmm requested changes
With https://github.com/wevm/wagmi/pull/4453 merged, might be better to add an `instantOnboarding` property to `connector.connect` so it's discoverable and easier for folks to use.

```ts
const { connect, connectors } = useConnect()
connect({
  connector: connectors[0],
  instantOnboarding: true, // <-- `instantOnboarding` type inferred, shows up in autocomplete, etc.
})
```
```ts
const config = createConfig({
  chains: [mainnet],
  connectors: [coinbaseWallet({ ... })],
  transports: { [mainnet.id]: http() },
})

declare module 'wagmi' {
  interface Register {
    config: typeof config
  }
}
```

2024-12-13 19:04 UTC, tmm commented on .changeset/big-radios-sip.md
> +Supports Instant Onboarding mode of Coinbase Smart Wallet
```suggestion
Added Coinbase Smart Wallet "Instant Onboarding" mode to `coinbaseWallet`.
```

2024-12-13 19:04 UTC, tmm commented on .changeset/big-radios-sip.md
> +"@wagmi/connectors": patch
New feature so `minor`

```suggestion
"@wagmi/connectors": minor
```

2024-12-16 22:03 UTC, merged

2024-12-24 00:16 UTC, johanneskares commented
just realized @tmm you finished this. Thanks a log 🙏